DesafioDotNet.Presentation/Models/AmigoViewModel.cs
using DesafioDotNet.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DesafioDotNet.Presentation.Models
{
    public class AmigoViewModel
    {
        public Pessoa Amigo { get; set; }
    }
}

DesafioDotNet.Presentation/Models/DatatablesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DesafioDotNet.Presentation.Models
{
    public class DatatablesViewModel
    {
        public string Id { get; set; }

        public DatatablesViewModel(string id)
        {
            Id = id;
        }
    }
}

DesafioDotNet.Presentation/Models/EmprestimoViewModel.cs
using DesafioDotNet.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DesafioDotNet.Presentation.Models
{
    public class EmprestimoViewModel
    {
        public PessoaJogo Emprestimo { get; set; }

        public List<Jogo> Jogos { get; set; }

        public List<Pessoa> Amigos { get; set; }
    }
}

DesafioDotNet.Presentation/Models/JogoViewModel.cs
using DesafioDotNet.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DesafioDotNet.Presentation.Models
{
    public class JogoViewModel
    {
        public Jogo Jogo { get; set; }
    }
}

DesafioDotNet.Presentation/Models/LoginViewModel.cs
using DesafioDotNet.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DesafioDotNet.Presentation.Models
{
    public class LoginViewModel
    {
        public Login Login { get; set; }
    }
}

DesafioDotNet.Presentation/Controllers/AmigoController.cs
using DesafioDotNet.Business;
using DesafioDotNet.Commom;
using DesafioDotNet.Entity;
using DesafioDotNet.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioDotNet.Presentation.Controllers
{
    [ValidadorLogin]
    public class AmigoController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Salvar(AmigoViewModel model)
        {
            var retorno = new BusinessPessoa().Salvar(model.Amigo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Excluir(AmigoViewModel model)
        {
            var retorno = new BusinessPessoa().Excluir(model.Amigo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Listar(ParametrosDataTables parametros)
        {
            var retorno = new BusinessPessoa().Listar(DefinirParametrosConsulta(parametros));

            if (retorno.IsValido)
                return Json(CriarDatatablesResponse(parametros, retorno.Entity as ResultadoDataTables<Pessoa>), JsonRequestBehavior.AllowGet);

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }
    }
}

DesafioDotNet.Presentation/Controllers/BaseController.cs
using DesafioDotNet.Commom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioDotNet.Presentation.Controllers
{
    public class BaseController : Controller
    {
        protected DatatablesResponse CriarDatatablesResponse<T>(ParametrosDataTables parametrosDataTable, ResultadoDataTables<T> retorno)
        {
            return new DatatablesResponse
            {
                aaData = retorno.Lista,
                iTotalDisplayRecords = retorno.QuantidadeRegistrosTotal,
                iTotalRecords = retorno.QuantidadeRegistros
            };
        }

        protected static ParametrosOrdenacaoPaginacao DefinirParametrosConsulta(ParametrosDataTables parametros)
        {
            return new ParametrosOrdenacaoPaginacao
            {
                Inicio = parametros.start,
                Quantidade = Constantes.QUANTIDADE_REGISTROS_PAGINA,
                CampoOrdenacao = parametros.order[0].column.ToString(),
                DirecaoOrdenacao = parametros.order == null ? String.Empty : parametros.order[0].dir
            };
        }

    }
}

DesafioDotNet.Presentation/Controllers/EmprestimoController.cs
using DesafioDotNet.Business;
using DesafioDotNet.Commom;
using DesafioDotNet.Entity;
using DesafioDotNet.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioDotNet.Presentation.Controllers
{
    [ValidadorLogin]
    public class EmprestimoController : BaseController
    {
        public ActionResult Index()
        {
            var jogos = new BusinessJogo().Listar().Entity as List<Jogo>;
            var amigos = new BusinessPessoa().Listar().Entity as List<Pessoa>;

            return View(new EmprestimoViewModel { Jogos = jogos, Amigos = amigos });
        }

        public JsonResult Salvar(EmprestimoViewModel model)
        {
            model.Emprestimo.Data = DateTime.Now;
            var retorno = new BusinessPessoaJogo().Salvar(model.Emprestimo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Excluir(EmprestimoViewModel model)
        {
            var retorno = new BusinessPessoaJogo().Excluir(model.Emprestimo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Listar(ParametrosDataTables parametros, string nomeAmigo, string descricaoJogo)
        {
            var retorno = new BusinessPessoaJogo().Pesquisar(new PessoaJogo()
            {
                Pessoa = new Pessoa { Nome = nomeAmigo },
                Jogo = new Jogo { Descricao = descricaoJogo }
            }, DefinirParametrosConsulta(parametros));

            if (retorno.IsValido)
                return Json(CriarDatatablesResponse(parametros, retorno.Entity as ResultadoDataTables<PessoaJogo>), JsonRequestBehavior.AllowGet);

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

    }
}

DesafioDotNet.Presentation/Controllers/JogoController.cs
using DesafioDotNet.Business;
using DesafioDotNet.Commom;
using DesafioDotNet.Entity;
using DesafioDotNet.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioDotNet.Presentation.Controllers
{
    [ValidadorLogin]
    public class JogoController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Salvar(JogoViewModel model)
        {
            var retorno = new BusinessJogo().Salvar(model.Jogo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Excluir(JogoViewModel model)
        {
            var retorno = new BusinessJogo().Excluir(model.Jogo);
            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Listar(ParametrosDataTables parametros)
        {
            var retorno = new BusinessJogo().Listar(DefinirParametrosConsulta(parametros));

            if (retorno.IsValido)
                return Json(CriarDatatablesResponse(parametros, retorno.Entity as ResultadoDataTables<Jogo>), JsonRequestBehavior.AllowGet);

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }
    }
}

DesafioDotNet.Presentation/Controllers/LoginController.cs
using DesafioDotNet.Business;
using DesafioDotNet.Commom;
using DesafioDotNet.Entity;
using DesafioDotNet.Presentation.ControleLogin;
using DesafioDotNet.Presentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioDotNet.Presentation.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Logar(LoginViewModel model)
        {
            var retorno = new BusinessLogin().Logar(model.Login);

            if (retorno.IsValido)
                Session[UsuarioLogado.SESSION_USUARIO_LOGADO] = (retorno.Entity as Login);

            return Json(retorno, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Logoff()
        {
            Session[UsuarioLogado.SESSION_USUARIO_LOGADO] = null;

            return View("Index");
        }

    }
}

DesafioDotNet.Presentation/Views/Amigo/Index.cshtml
@using DesafioDotNet.Presentation.Models;
@model DesafioDotNet.Presentation.Models.AmigoViewModel

@{
    ViewBag.Title = "Amigos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AMIGOS</h2>

@using (Html.BeginForm())
{
    <h3>CADASTRO</h3>
    <br />
    <fieldset>
        <legend></legend>

        @Html.HiddenFor(model => model.Amigo.Codigo, new { id = "hdnCodigo" })

        <div>
            <div class="editor-label">
                @Html.Label("", "*Nome")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Amigo.Nome, new { id = "txtNome", @class = "js-obrigatorio" })
            </div>
        </div>

        <div>
            <div class="editor-label">
                @Html.Label("", "Apelido")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Amigo.Apelido, new { id = "txtApelido" })
            </div>
        </div>

        <p>
            <input id="btnSalvar" type="submit" value="Salvar" />
            <input id="btnCancelar" class="invisivel" type="submit" value="Cancelar" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/_Datatables.cshtml", new DatatablesViewModel("tblAmigos"))
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Amigo/Index.js"></script>
}

DesafioDotNet.Presentation/Views/Emprestimo/Index.cshtml
@using DesafioDotNet.Presentation.Models;
@model DesafioDotNet.Presentation.Models.EmprestimoViewModel

@{
    ViewBag.Title = "Emprestimos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EMPRESTIMOS</h2>

@using (Html.BeginForm())
{
    <section class="float_left">
        <h3>CADASTRO</h3>
        <br />
        <fieldset>
            <legend></legend>

            @Html.HiddenFor(model => model.Emprestimo.Codigo, new { id = "hdnCodigo" })

            <div>
                <div class="form-group">
                    @Html.Label("", "*Amigo")
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.Emprestimo.Pessoa.Codigo, new SelectList(Model.Amigos.Select(x => x), "Codigo", "Nome"), "Selecione...", new { id = "ddlAmigo", @class = "form-control js-obrigatorio" })
                </div>
            </div>

            <div>
                <div class="editor-label">
                    @Html.Label("", "*Jogo")
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.Emprestimo.Jogo.Codigo, new SelectList(Model.Jogos, "Codigo", "Descricao"), "Selecione...", new { id = "ddlJogo", @class = "js-obrigatorio" })
                </div>
            </div>

            <p>
                <input id="btnSalvar" type="submit" value="Salvar" />
                <input id="btnCancelar" class="invisivel" type="submit" value="Cancelar" />
            </p>
        </fieldset>
    </section>
    
    <section class="float_right">
        <h3>PESQUISA</h3>
        <br />
        <fieldset>
            <legend></legend>

            <div class="editor-label">
                @Html.Label("", "Amigo")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Emprestimo.Pessoa.Nome, new { id = "txtNomeAmigo" })
            </div>

            <div class="editor-label">
                @Html.Label("", "Jogo")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Emprestimo.Jogo.Descricao, new { id = "txtDescricaoJogo" })
            </div>

            <p>
                <input id="btnConsultar" type="submit" value="Consultar" />
            </p>
        </fieldset>
    </section>
}

<div>
    @Html.Partial("~/Views/Shared/_Datatables.cshtml", new DatatablesViewModel("tblEmprestimos"))
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Emprestimo/Index.js"></script>
}

DesafioDotNet.Presentation/Views/Jogo/Index.cshtml
@using DesafioDotNet.Presentation.Models;
@model DesafioDotNet.Presentation.Models.JogoViewModel

@{
    ViewBag.Title = "Jogos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>JOGOS</h2>

@using (Html.BeginForm())
{
    <h3>CADASTRO</h3>
    <br />
    <fieldset>
        <legend></legend>

        @Html.HiddenFor(model => model.Jogo.Codigo, new { id = "hdnCodigo" })

        <div>
            <div class="editor-label">
                @Html.Label("", "*Descrição")
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.Jogo.Descricao, new { id = "txtDescricao", @class = "js-obrigatorio" })
            </div>
        </div>

        <p>
            <input id="btnSalvar" type="submit" value="Salvar" />
            <input id="btnCancelar" class="invisivel" type="submit" value="Cancelar" />
        </p>
    </fieldset>
}

<div>
    @Html.Partial("~/Views/Shared/_Datatables.cshtml", new DatatablesViewModel("tblJogos"))
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Jogo/Index.js"></script>
}

DesafioDotNet.Presentation/Views/Login/Index.cshtml
@model DesafioDotNet.Presentation.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<section id="loginForm">
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Login</legend>
            <ol>
                <li>
                    @Html.Label("", "*Usuário")
                    @Html.TextBoxFor(m => m.Login.Usuario, new { @class = "js-obrigatorio" })
                </li>
                <li>
                    @Html.Label("", "*Senha")
                    @Html.PasswordFor(m => m.Login.Senha, new { @class = "js-obrigatorio" })
                </li>
            </ol>
            <input id="btnLogar" type="submit" value="Logar" />
        </fieldset>
    }
</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Login/Index.js"></script>
}

DesafioDotNet.Presentation/Views/Shared/_Layout.cshtml
@using DesafioDotNet.Commom;
@using DesafioDotNet.Presentation.ControleLogin;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - DesafioDotNet</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/geral.css" rel="stylesheet" />
</head>
<body>


    <header>
        <div class="content-wrapper">
            <div class="float-left">
            </div>
            <div class="float-right">
                @if (UsuarioLogado.EstaLogado)
                {                    
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("AMIGOS", "Index", "Amigo")</li>
                            <li>@Html.ActionLink("JOGOS", "Index", "Jogo")</li>
                            <li>@Html.ActionLink("EMPRESTIMOS", "Index", "Emprestimo")</li>
                            <li>@Html.ActionLink("LOGOFF", "Logoff", "Login")</li>
                        </ul>
                    </nav>
                    
                    <div class="float-right">
                        @{
                    var saudacao = DateTime.Now.Hour > 12 ? "Boa tarde" : "Bom dia";
                            <label>@saudacao <b><i>@UsuarioLogado.Usuario.Pessoa.Nome</i></b>.</label>
                        }
                    </div>
                }
            </div>
        </div>
    </header>

    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - DesafioDotNet</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Geral.js"></script>
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script type="text/javascript">
        var rootUrl = "@Url.Content("~")";

        var MSG_08 = '@Html.Raw(@Mensagens.MSG_08)';
        var MSG_09 = '@Html.Raw(@Mensagens.MSG_09)';

    </script>
</body>
</html>

DesafioDotNet.Presentation/Views/Shared/_dataTables.cshtml
@using DesafioDotNet.Presentation.Models;

@model DatatablesViewModel

<div>
    <table id="@Model.Id" class="table table-hover table-striped" width="100%"></table>

    <div id="@(Model.Id)InfoMessage" class="alert alert-info datatables-info" role="alert" style="display:none;">
        <span class="icon-info-sign"></span>
        <strong>Informação!</strong><span class="js-mensagem"></span>
    </div>
    <div id="@(Model.Id)ErrorMessage" class="alert alert-info datatables-error" role="alert" style="display:none;">
        <span class="icon-remove-sign"></span>
        <strong>Erro técnico!</strong>
        <div class="datatables-error-details"></div>
    </div>
</div>